EXAMES_DISPONIVEIS_CLINICA = [
    "Hemograma Completo",
    "Glicemia de Jejum",
    "Perfil Lipídico (Colesterol Total e Frações)",
    "Ureia e Creatinina",
    "Ácido Úrico",
    "Urina Tipo I",
    "Exame Parasitológico de Fezes",
    "Eletrocardiograma (ECG)",
    "Ecocardiograma",
    "Teste Ergométrico (Esteira)",
    "Holter 24h",
    "M.A.P.A. 24h",
    "Raio-X do Tórax",
    "Ultrassonografia Abdominal",
    "Tomografia Computadorizada do Crânio",
    "Ressonância Magnética do Joelho",
    "Mamografia",
    "Densitometria Óssea",
    "Endoscopia Digestiva Alta",
    "Colonoscopia",
    "Papanicolau",
    "Exame de PSA (Próstata)",
    "Eletroencefalograma (EEG)",
    "Biópsia de Pele",
    "Exame de Fundo de Olho"
]